services:
    db:
        image: ankane/pgvector:latest
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - pgdata2:/var/lib/postgresql/data
        ports:
            - "5433:5432"

volumes:
    pgdata2:
