apiVersion: v1
kind: Service
metadata:
    labels:
        app: demo
    name: demo-svc
spec:
    ports:
        - name: http
          port: 8000
          protocol: TCP
          targetPort: 8000
    selector:
        app: demo
